help: "```!помощь - Команды бота.```\n
```!инфо optional:user - Информация о пользователе.```\n
```!дота id - Обновить свой dota id.```\n
```!рег - Зарегестрироваться на турнир.```\n
```!анрег - Отмена регистрации на турнир.```\n
```!соулс - Мне нужно больше душ. Покупка душ за деньги.```\n
```!tm кому сколько - Перевод денег пользователю.```\n
```!перевод кому сколько - Перевод душ пользователю.```\n
```!коуч - Коучинг.```\n
```!роль - Покупка ролей. (!роль помощь - все команды)```\n"

tournament_help: "**?create_tournament** - создание турнира
**?remove_tournament** - удаление турнира 
**?cancel_tournament** - отмена турнира. возврат средств участникам.
**?reglist** - список участников
**?rzxc** - забрать у всех роль zxc member"

moderation_help: "**?ban** `user` - забанить пользователя
**?voicemute** `user` `time` `reason` - замутить пользователя в голосовом чате. Без указания времени замутит навсегда. 
**?chatmute** `user` `time` `reason` - замутить пользователя в текстовом чате. Без указания времени замутит навсегда."

finance_help: "**?tub** `user` `amount` - изменить баланс пользователя 
**?givesouls** `user` `amount` - выдать душу пользователю
**?finance** - баланс админов

**Examples:**
`?tub @user 150` **or** `?tub @user -300`
`?givesouls @user 228` **or** `?givesouls @user -1337`"

coach_moderation_help: "**?add_coach** `user` `tier` - добавить коучера
**?remove_coach** `user` - удалить коучера"

ban_alert: "**{user}** был забанен."

specify_user: "Укажите пользователя"

infinite_voice_mute_alert: "Пользователь {user} был замучен в голосовом чате на неопределенный срок админом {admin}.
Причина: {reason}"

voice_mute_alert: "Пользователь {user} был замучен в голосовом чате на {time} минут админом {admin}\nПричина: {reason}"

voice_unmute_alert: "Пользователь {user} был размучен в голосовом чате!"

infinite_chat_mute_alert: "Пользователь {user} был замучен в текстовом чате на неопределенный срок админом {admin}.
Причина: {reason}"

chat_mute_alert: "Пользователь {user} был замучен в текстовом чате на {time} минут админом {admin}\nПричина: {reason}"

chat_unmute_alert: "Пользователь {user} был размучен в текстовом чате!"

unmute_alert: "Пользователь {user} был размучен {admin}"

role_shop_help: "**Стоимость:**
\n
• активация: 30000 душ на 30 дней\n
• продление: 500 душ за 1 день\n
• выдача роли: 500 душ за 1 пользователя\n
• изменение цвета/названия: 2000 душ\n
\n
**Возможности:**\n
• выдача роли другим пользователям\n
• выставление роли на продажу в магазин\n
\n
**Доп. правила:**\n
Название роли не должно содержать: оскорбления, рекламу или же нацистскую символику\n
Роли с названием Tier 1, Tier 1 SF и т.п будут удаляться без функции возврата душ на баланс.\n
Роль не должна быть копией серверной роли или другой личной\n
\n
**Доп. информация:**\n
Для указания цвета используется hex-палитра. Найти подходящий цвет можно [здесь](https://colorscheme.ru/color-converter.html)\n
\n
!роль **магазин** - Список ролей на продаже\n
!роль **создать** `#ff80ed` `сф` - Создать роль\n
!роль **продлить** `@роль` `30` - Продлить роль (В разработке)\n
!роль **цвет** `@роль` `#ff80ed` - Изменить цвет роли\n
!роль **имя** `@роль` `пудж` - Изменить наименование роли (В разработке)\n
!роль **+** `@роль` `@пользователь` - Выдать роль пользователю (В разработке)\n
!роль **-** `@роль` `@пользователь` - Забрать роль у пользователя (В разработке)\n
!роль **инфо** `@роль` - Информация о роли\n
!роль **продажа** `@роль` - Выставить роль на продажу\n
!роль **цена** `@роль` `цена` - Изменить стоимость роли\n
!роль **купить** `@роль`'"
